In [148]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score,confusion_matrix
from sklearn.preprocessing import MinMaxScaler

In [149]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

In [150]:
path = '../corpus/breast-cancer-wisconsin.data'
with open(path, 'r') as f:
    lines = f.readlines()
lines=[l.strip().replace('?','5').split(',') for l in lines]
lines = np.array(lines)
ids = lines[:,0].astype(np.int)
x = lines[:,1:-1].astype(np.float)

labels = lines[:,-1].astype(np.int)
labels = labels/2-1
y = labels.astype(np.float)
y = y/2-1


In [151]:
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)

In [152]:
epoch = 60000
lr = 0.03

b,d = x.shape

y = np.reshape(y, (b,1))

h = 100
c = 2

mu, sigma = 0,0.04


In [155]:
np.random.seed(4444)
W1 = np.random.random( (d,h)) -1
W2 = np.random.random( (h,c)) -1

In [156]:
for e in range(epoch):
    # Forward path
    z1 = np.dot(x, W1) 
    l1 = sigmoid(z1)
    z2 = np.dot(l1, W2)
    l2 = sigmoid(z2)
    # Back-propagation
    
    err = l2 - y

    if e % 100 ==0:
        y_pred = np.argmax(l2, axis=1)
        loss = np.sum(np.square(err)) / b
        acc = accuracy_score(labels, y_pred)
        f = f1_score(labels, y_pred)
        print('Epoch %d: loss=%0.4f > acc=%0.4f > f0=%0.4f'%(e, loss, acc, f))
        print(confusion_matrix(labels, y_pred))
    
    e_z2 = err * l2 * (1-l2)
    
    delta_W2 = np.dot(l1.T, e_z2)
    
    e_l1 = np.dot(e_z2, W2.T)
    
    e_z1 = e_l1 * l1 * (1-l1)
    
    delta_W1 = np.dot(x.T, e_z1)
    
    W1 = W1 + lr * delta_W1
    W2 = W2 + lr * delta_W2


Epoch 0: loss=1.5209 > acc=0.3262 > f0=0.4897
[[  2 456]
 [ 15 226]]
Epoch 100: loss=6.7931 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 200: loss=6.7932 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 300: loss=6.7932 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 400: loss=6.7932 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 500: loss=6.7932 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 600: loss=6.7932 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 700: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 800: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 900: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 1000: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 1100: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 1200: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoch 1300: loss=6.7933 > acc=0.3448 > f0=0.5128
[[  0 458]
 [  0 241]]
Epoc

KeyboardInterrupt: 