In [137]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score,confusion_matrix
from sklearn.preprocessing import MinMaxScaler
import torch 
import torch.nn as nn
import torch.optim as optim
from torch.autograd import Variable

In [138]:
path = '../corpus/breast-cancer-wisconsin.data'
with open(path, 'r') as f:
    lines = f.readlines()
# lines = lines[:2]
lines=[l.strip().replace('?','5').split(',') for l in lines]
lines = np.array(lines)
ids = lines[:,0].astype(np.int)
x = lines[:,1:-1].astype(np.float)

y = lines[:,-1].astype(np.int)
y = y/2-1

In [139]:
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)

In [140]:
epoch = 12000
lr = 0.01

In [141]:
model = nn.Sequential(
    nn.Linear(9,h),
    nn.Sigmoid(),
    nn.Linear(h,h),
    nn.Sigmoid(),
    nn.Linear(h,2)
)
optimizer = torch.optim.SGD(model.parameters(), lr=lr)  
weight = torch.FloatTensor(np.array([1,2]))
criterion = nn.CrossEntropyLoss(weight=weight)

In [142]:
features = Variable(torch.from_numpy(x).type(torch.FloatTensor))
target = Variable(torch.from_numpy(y))
for e in range(epoch):
    y_hat = model(features)
    loss = criterion(y_hat, target)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    if e % 1000 == 0:
        _, y_pred = torch.max(y_hat, 1)
        y_pred = y_pred.data.numpy()
        
        acc = accuracy_score(y, y_pred)
        f = f1_score(y, y_pred)
        cm = confusion_matrix(y, y_pred)
        print('Epoch %d: %f > %f > %f'%(e, loss.data[0], acc, f))
        print(cm)

    


Epoch 0: 0.711122 > 0.344778 > 0.512766
[[  0 458]
 [  0 241]]
Epoch 1000: 0.659052 > 0.924177 > 0.900563
[[406  52]
 [  1 240]]
Epoch 2000: 0.562569 > 0.969957 > 0.956879
[[445  13]
 [  8 233]]
Epoch 3000: 0.332618 > 0.965665 > 0.950413
[[445  13]
 [ 11 230]]
Epoch 4000: 0.172690 > 0.967096 > 0.952577
[[445  13]
 [ 10 231]]
Epoch 5000: 0.122242 > 0.969957 > 0.956879
[[445  13]
 [  8 233]]
Epoch 6000: 0.104589 > 0.969957 > 0.956879
[[445  13]
 [  8 233]]
Epoch 7000: 0.096908 > 0.969957 > 0.956879
[[445  13]
 [  8 233]]
Epoch 8000: 0.092967 > 0.971388 > 0.959016
[[445  13]
 [  7 234]]
Epoch 9000: 0.090670 > 0.969957 > 0.957055
[[444  14]
 [  7 234]]
Epoch 10000: 0.089186 > 0.971388 > 0.959184
[[444  14]
 [  6 235]]
Epoch 11000: 0.088138 > 0.971388 > 0.959184
[[444  14]
 [  6 235]]
