In [1]:
import numpy as np
from sklearn.metrics import accuracy_score, f1_score,confusion_matrix, precision_recall_fscore_support 
from sklearn.preprocessing import MinMaxScaler
import tensorflow as tf

In [2]:
path = '../corpus/breast-cancer-wisconsin.data'
with open(path, 'r') as f:
    lines = f.readlines()
# lines = lines[:2]
lines=[l.strip().replace('?','5').split(',') for l in lines]
lines = np.array(lines)
ids = lines[:,0].astype(np.int)
x = lines[:,1:-1].astype(np.float)

labels = lines[:,-1].astype(np.int)
labels = labels/2-1

n,d = x.shape


y  = np.zeros((n,2))
y[np.arange(n), labels] = 1
print(y)

[[1. 0.]
 [1. 0.]
 [1. 0.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [3]:
scaler = MinMaxScaler()
scaler.fit(x)
x = scaler.transform(x)

In [16]:
epoch = 12000
h = 100
lr = 0.01
b = 50

In [5]:
x_pl = tf.placeholder(tf.float32, shape=[None, d])
y_pl = tf.placeholder(tf.int32, shape=[None,2])

In [6]:
w1 = tf.get_variable('w1',shape=[d, h],dtype=tf.float32)
w2 = tf.get_variable('w2',shape=[h, 2],dtype=tf.float32)

In [11]:
l1 = tf.sigmoid(tf.matmul(x_pl, w1))
l2 = tf.sigmoid(tf.matmul(l1, w2))

loss = tf.reduce_sum(tf.nn.softmax_cross_entropy_with_logits(labels=y_pl, logits=l2))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=lr)
train_op = optimizer.minimize(loss)

In [14]:
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)

In [18]:
log =[]

for e in range(epoch):
    feeddict = {x_pl: x, y_pl: y}
    l, y_hat,_ = sess.run(feed_dict=feeddict, fetches=[loss, l2, train_op])
    if e % 1000 == 0:
        y_pred = np.argmax(y_hat,axis=1)
        
        acc = accuracy_score(labels, y_pred)
        p,r,f,_ = precision_recall_fscore_support(labels, y_pred)
        #cm = confusion_matrix(y, y_pred)
        log.append((e, l, f[0],f[1]))
        print('Epoch %d: %f > %f > %f'%(e, l, f[0],f[1]))
        print(confusion_matrix(labels, y_pred))
print('DONE')

Epoch 0: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 1000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 2000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 3000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 4000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 5000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 6000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 7000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 8000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 9000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 10000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
Epoch 11000: 459.970520 > 0.791703 > 0.000000
[[458   0]
 [241   0]]
DONE


In [10]:
from matplotlib import pyplot as plt
epochs, losses, f0, f1 = zip(*log)
figure = plt.plot(epochs, losses, 'r-',epochs,f0,'b-',epochs,f1,'g-')
plt.show()

<Figure size 640x480 with 1 Axes>